version: 2.1

orbs:
  hugo: circleci/hugo@0.4.1

executors:
  default:
    docker:
      - image: cimg/base:2021.04

commands:
  install_firebase_tools:
    steps:
      - run:
          name: Install firebase-tools
          command: curl -sL https://firebase.tools | bash

jobs:
  deploy:
    executor:
      name: default
    steps:
      - checkout
      - attach_workspace:
          at: my-site
      - run:
          name: Link Built Sites
          command: ln -snf my-site/public public
      - install_firebase_tools
      - run:
          name: Deploy to Firebase
          command: firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - hugo/build:
          html-proofer: false
          source: .
          version: "0.60"

      - deploy:
          context: Firebase
          filters:
            branches:
              only:
                - master
          requires:
            - hugo/build
