version: 2.1
orbs:
  hugo: circleci/hugo@0.4.1
jobs:
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: my-site
      - run:
          name: Link Built Sites
          command: ln -snf my-site/public public
      - run:
          name: Install npm modules
          command: npm ci
      - run:
          name: Deploy to Firebase
          command: npx firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - hugo/build:
          html-proofer: false
          source: .
          version: '0.60'
      - deploy:
          context: Firebase
          filters:
            branches:
              only:
                - master
          requires:
            - hugo/build
