version: 2.1
orbs:
  hugo: circleci/hugo@0.4.1
jobs:
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: my-site
      - run: ls -lah my-site

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - hugo/build:
          html-proofer: true
          source: .
          version: '0.60'
      - deploy:
          filters:
            only:
              branches:
                - master
          requires:
            - hugo/build
